### ISSUE TITLE
sleep(SleepTime) Issue

### ISSUE THREAD

**Issue by porteriscool** [darkgoldblade01/BeamPro-ComputerCraft-Stats#1]
The monitors aren't reloading after the initial 60 seconds and updating the monitors.
This streamer is no longer live, and the information on the monitor hasn't updated.
![2015-08-26_17 41 34](https://cloud.githubusercontent.com/assets/12450943/9507226/a3a84e0e-4c1a-11e5-868e-564129e56622.png)

**Comment by brianclogan** [comment]
WOW, so sorry for the delay! I am looking into it, and will let you know if I find anything! <3 <3

Sorry for the delay! If this is an issue with the Beam script, it most likely exists also in the Twitch one as well. I will keep you up to date if I find anything!

**Comment by brianclogan** [comment]
Sorry for the delay in the response. There isn't any issues with the repeat or the sleep time, it could be a delay in the API update. I will see if I can still duplicate the issue, but so far no success.

**Comment by brianclogan** [comment]
If I duplicate the issue, I will reopen the issue.
