### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by TheBaconSpace** [darkgoldblade01/BeamPro-ComputerCraft-Stats#2]
is it possible to track Subs someone Requested it

**Comment by brianclogan** [comment]
I will look into seeing if it is possible with the Beam API, I am not sure
of the top of my head. Along what lines to do you want to track subs? Want
to track the number, or....

On Sat, Jan 23, 2016 at 11:45 AM, Bacon_Space notifications@github.com
wrote:

> is it possible to track Subs someone Requested it
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/darkgoldblade01/BeamPro-ComputerCraft-Stats/issues/2.

## 

Brian Logan
(480)-296-8857

**Comment by TheBaconSpace** [comment]
@darkgoldblade01 i putted a pull Request for updating with Sparks if u ever want to work with u for StreamStats Email me at thestreamstats@gmail.com will get back to you

**Comment by brianclogan** [comment]
I merged to the master and updated the pastebin to the latest version.
